{% set name = "markitdown" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c956ff1528bf15e1814542035ec96e989206d19d311bb799f4df973ecafc31a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # magika dep has no py314 build; numpy/mkl/onnxruntime cyclic dep on win py3.10
  skip: true  # [py<310 or py>313 or (win and py==310)]
  entry_points:
    - markitdown = markitdown.__main__:main

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - beautifulsoup4
    - requests
    - markdownify
    - magika >=0.6.1,<0.7.dev0
    - charset-normalizer
    - defusedxml

test:
  imports:
    - markitdown
  requires:
    - pip
  commands:
    - pip check

about:
  summary: Utility tool for converting various files to Markdown
  license: MIT
  license_file: LICENSE
  license_family: MIT
  home: https://github.com/microsoft/markitdown
  description: |
    Python tool for converting files and office documents to Markdown.
  doc_url: https://github.com/microsoft/markitdown
  dev_url: https://github.com/microsoft/markitdown

extra:
  recipe-maintainers:
    - johnhany97
    - sarthakpati
